services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=shortin_db'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=shortin'
    ports:
      - '5432'
