CREATE TABLE urls(
	id SERIAL,
	long_url VARCHAR(255) UNIQUE NOT NULL,
	short_url VARCHAR(5) UNIQUE NOT NULL,
	created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	expire_at TIMESTAMPTZ,
	CONSTRAINT urls_pkey PRIMARY KEY (id)
);